-- =============================================================
-- FILE: 310_sultandefense_news.seed.sql
-- Sultan Defense — News (custom_pages) + i18n (TR/EN)
-- module_key = 'news'
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

START TRANSACTION;

INSERT INTO `custom_pages`
(
  `id`, `module_key`, `is_published`, `featured`, `display_order`, `order_num`,
  `featured_image`, `featured_image_asset_id`, `image_url`, `storage_asset_id`,
  `images`, `storage_image_ids`, `category_id`, `sub_category_id`
)
VALUES
  ('nw010001-5001-4001-9001-nnnnnnnn0001', 'news', 1, 1, 10, 10, '/media/sultandefense/news-procurement-portfolio.jpg', NULL, '/media/sultandefense/news-procurement-portfolio.jpg', NULL, '[]', '[]', 'nc010001-4001-4001-8001-000000000001', NULL),
  ('nw010002-5002-4002-9002-nnnnnnnn0002', 'news', 1, 1, 20, 20, '/media/sultandefense/news-export-compliance.jpg', NULL, '/media/sultandefense/news-export-compliance.jpg', NULL, '[]', '[]', 'nc010002-4002-4002-8002-000000000002', NULL),
  ('nw010003-5003-4003-9003-nnnnnnnn0003', 'news', 1, 0, 30, 30, '/media/sultandefense/news-regional-logistics.jpg', NULL, '/media/sultandefense/news-regional-logistics.jpg', NULL, '[]', '[]', 'nc010003-4003-4003-8003-000000000003', NULL),
  ('nw010004-5004-4004-9004-nnnnnnnn0004', 'news', 1, 0, 40, 40, '/media/sultandefense/news-tactical-technology.jpg', NULL, '/media/sultandefense/news-tactical-technology.jpg', NULL, '[]', '[]', 'nc010004-4004-4004-8004-000000000004', NULL),
  ('nw010005-5005-4005-9005-nnnnnnnn0005', 'news', 1, 1, 50, 50, '/media/sultandefense/news-defense-standards.jpg', NULL, '/media/sultandefense/news-defense-standards.jpg', NULL, '[]', '[]', 'nc010005-4005-4005-8005-000000000005', NULL)
ON DUPLICATE KEY UPDATE
  `module_key` = VALUES(`module_key`),
  `is_published` = VALUES(`is_published`),
  `featured` = VALUES(`featured`),
  `display_order` = VALUES(`display_order`),
  `featured_image` = VALUES(`featured_image`),
  `image_url` = VALUES(`image_url`),
  `images` = VALUES(`images`),
  `category_id` = VALUES(`category_id`);

INSERT INTO `custom_pages_i18n`
(`id`, `page_id`, `locale`, `title`, `slug`, `content`, `summary`, `meta_title`, `meta_description`, `tags`)
VALUES
  ('nw020001-6001-4001-a001-nnnnnnnn0001', 'nw010001-5001-4001-9001-nnnnnnnn0001', 'tr', 'Sultan Defense Savunma Tedarik Portfoyunu Yayina Aldi', 'sultan-defense-savunma-tedarik-portfoyu', JSON_OBJECT('html', '<p>Sultan Defense, kara sistemleri, balistik koruma, taktik tekstil, optik, elektronik ve lojistik destek kalemlerini kapsayan savunma tedarik portfoyunu yayina aldi.</p><h2>B2B odakli katalog</h2><p>Katalog, kamu kurumlari, guvenlik birimleri ve yetkili ticari alicilar icin urun ailelerini sade ve karsilastirilabilir sekilde sunar.</p><h2>Tedarik sureci</h2><p>Teknik gereksinim toplama, uretici dogrulama, ihracat uyumu, kalite kabul ve sevkiyat planlama adimlari tek is akisi olarak yurutulur.</p>'), 'Sultan Defense savunma tedarik portfoyu ve B2B katalog yapisi hakkinda duyuru.', 'Sultan Defense Savunma Tedarik Portfoyu | Haberler', 'Sultan Defense kara sistemleri, balistik koruma, taktik tekstil, optik ve elektronik tedarik portfoyunu yayina aldi.', 'savunma tedariki, B2B katalog, Sultan Defense'),
  ('nw020002-6002-4002-a002-nnnnnnnn0002', 'nw010002-5002-4002-9002-nnnnnnnn0002', 'tr', 'EUC ve Ihracat Izin Dosyalari Icin Yeni Kontrol Akisi', 'euc-ihracat-izin-kontrol-akisi', JSON_OBJECT('html', '<p>Sultan Defense, son kullanici belgesi ve ihracat izin dosyalarinin teklif asamasinda kontrol edilmesi icin standart bir on inceleme akisi devreye aldi.</p><h2>On kontrol</h2><p>Alici bilgisi, nihai kullanim amaci, hedef ulke, urun teknik kodlari ve dokuman tutarliligi erken asamada dogrulanir.</p><h2>Daha az gecikme</h2><p>Eksik belge kaynakli gecikmeleri azaltmak icin uretici, alici ve lojistik taraflari ayni dokuman seti uzerinden koordine edilir.</p>'), 'EUC, ihracat izni ve dokuman tutarliligi icin standart kontrol akisi.', 'EUC ve Ihracat Izin Kontrol Akisi | Sultan Defense', 'Sultan Defense son kullanici belgesi, ihracat izni ve dokuman uyumu icin yeni on kontrol akisi uyguluyor.', 'EUC, ihracat izni, export compliance'),
  ('nw020003-6003-4003-a003-nnnnnnnn0003', 'nw010003-5003-4003-9003-nnnnnnnn0003', 'tr', 'Orta Dogu, Afrika ve Turk Cumhuriyetleri Icin Lojistik Planlama', 'bolgesel-savunma-lojistik-planlama', JSON_OBJECT('html', '<p>Savunma urunlerinde sevkiyat planlamasi rota secimi, gumruk dokumanlari, ambalaj, tasima modu ve teslim sekli kararlarini birlikte gerektirir.</p><h2>Bolge bazli yaklasim</h2><p>Orta Dogu, Afrika ve Turk Cumhuriyetleri icin operasyonel gereksinimler, transit riskleri ve yerel ithalat kurallari ulke bazinda degerlendirilir.</p><h2>Izlenebilirlik</h2><p>Sultan Defense, teslimat surecinde dokuman takibi ve paydas koordinasyonunu merkezi olarak yurutur.</p>'), 'Hedef pazarlarda savunma lojistigi ve sevkiyat planlamasina dair ozet.', 'Bolgesel Savunma Lojistik Planlama | Sultan Defense', 'Savunma urunleri icin Orta Dogu, Afrika ve Turk Cumhuriyetleri odakli lojistik planlama.', 'askeri lojistik, savunma sevkiyat, gumruk'),
  ('nw020004-6004-4004-a004-nnnnnnnn0004', 'nw010004-5004-4004-9004-nnnnnnnn0004', 'tr', 'Taktik Haberlesme ve Sensor Taleplerinde Artis', 'taktik-haberlesme-sensor-talepleri', JSON_OBJECT('html', '<p>Saha birlikleri ve kritik tesis guvenligi icin taktik haberlesme, sensor, optik ve simülasyon ekipmanlarina yonelik talepler artiyor.</p><h2>Uyumluluk onceligi</h2><p>Mevcut sistemlerle entegrasyon, frekans, guc, iklim dayanimi ve egitim ihtiyaci teknik degerlendirmenin merkezinde yer alir.</p><h2>Paket cozum</h2><p>Sultan Defense, ekipman, aksesuar, yedek parca ve egitim gereksinimlerini birlikte degerlendirerek tedarik dosyasi hazirlar.</p>'), 'Taktik haberlesme, sensor ve optik taleplerinde teknik uyumluluk odagi.', 'Taktik Haberlesme ve Sensor Talepleri | Sultan Defense', 'Taktik haberlesme, sensor, optik ve simülasyon ekipmanlarinda uyumluluk ve tedarik notlari.', 'taktik haberlesme, sensor, optik, simülasyon'),
  ('nw020005-6005-4005-a005-nnnnnnnn0005', 'nw010005-5005-4005-9005-nnnnnnnn0005', 'tr', 'NATO, AQAP, MIL-STD, NIJ ve NSN Standartlari', 'savunma-standartlari-nato-aqap-mil-std-nij-nsn', JSON_OBJECT('html', '<p>Savunma tedarikinde standart referanslari, urun kalitesini ve operasyonel uygunlugu karsilastirilabilir hale getirir.</p><h2>Standart setleri</h2><p>NATO, AQAP, MIL-STD, NIJ, ISO 9001 ve NSN referanslari urun ailesine gore farkli anlamlar tasir. Dogru standart, dogru kullanim senaryosuyla eslestirilmelidir.</p><h2>Belge dogrulama</h2><p>Sultan Defense, sertifika ve teknik dokumanlari teklif dosyasi icinde kontrol ederek alici kararini destekler.</p>'), 'Savunma tedarikinde standart ve sertifika referanslarini anlamak icin kisa rehber.', 'Savunma Standartlari | Sultan Defense', 'NATO, AQAP, MIL-STD, NIJ, ISO 9001 ve NSN standartlarinin savunma tedarikindeki rolu.', 'NATO, AQAP, MIL-STD, NIJ, NSN'),
  ('nw020006-6006-4006-a006-nnnnnnnn0006', 'nw010001-5001-4001-9001-nnnnnnnn0001', 'en', 'Sultan Defense Publishes Its Defense Procurement Portfolio', 'sultan-defense-procurement-portfolio', JSON_OBJECT('html', '<p>Sultan Defense has published its procurement portfolio covering land systems, ballistic protection, tactical textile, optics, electronics, and logistics support items.</p><h2>B2B catalog focus</h2><p>The catalog presents product families in a clear and comparable structure for public institutions, security units, and authorized commercial buyers.</p><h2>Procurement workflow</h2><p>Requirement intake, manufacturer validation, export compliance, quality acceptance, and shipment planning are managed as one workflow.</p>'), 'Announcement of Sultan Defense procurement portfolio and B2B catalog structure.', 'Sultan Defense Procurement Portfolio | News', 'Sultan Defense publishes its land systems, ballistic protection, tactical textile, optics, and electronics procurement portfolio.', 'defense procurement, B2B catalog, Sultan Defense'),
  ('nw020007-6007-4007-a007-nnnnnnnn0007', 'nw010002-5002-4002-9002-nnnnnnnn0002', 'en', 'New Review Flow for EUC and Export Permit Files', 'euc-export-permit-review-flow', JSON_OBJECT('html', '<p>Sultan Defense has introduced a standard pre-review flow for end-user certificates and export permit files during quotation.</p><h2>Pre-check</h2><p>Buyer identity, end use, destination country, product technical codes, and document consistency are reviewed early.</p><h2>Fewer delays</h2><p>To reduce missing-document delays, manufacturer, buyer, and logistics parties are coordinated through the same document set.</p>'), 'Standard review flow for EUC, export permits, and document consistency.', 'EUC and Export Permit Review Flow | Sultan Defense', 'Sultan Defense applies a new pre-review flow for end-user certificates, export permits, and document compliance.', 'EUC, export permit, export compliance'),
  ('nw020008-6008-4008-a008-nnnnnnnn0008', 'nw010003-5003-4003-9003-nnnnnnnn0003', 'en', 'Logistics Planning for the Middle East, Africa, and Turkic Republics', 'regional-defense-logistics-planning', JSON_OBJECT('html', '<p>Shipment planning for defense products combines route selection, customs documents, packaging, transport mode, and delivery terms.</p><h2>Region-specific approach</h2><p>For the Middle East, Africa, and Turkic Republics, operational requirements, transit risks, and local import rules are assessed country by country.</p><h2>Traceability</h2><p>Sultan Defense centrally manages document tracking and stakeholder coordination during delivery.</p>'), 'A brief note on defense logistics and shipment planning for target regions.', 'Regional Defense Logistics Planning | Sultan Defense', 'Logistics planning for defense products focused on the Middle East, Africa, and Turkic Republics.', 'military logistics, defense shipment, customs'),
  ('nw020009-6009-4009-a009-nnnnnnnn0009', 'nw010004-5004-4004-9004-nnnnnnnn0004', 'en', 'Rising Demand for Tactical Communications and Sensors', 'tactical-communications-sensor-demand', JSON_OBJECT('html', '<p>Demand is rising for tactical communications, sensor, optics, and simulation equipment for field units and critical facility security.</p><h2>Compatibility first</h2><p>Integration with existing systems, frequency, power, climate resistance, and training needs sit at the center of technical review.</p><h2>Package approach</h2><p>Sultan Defense prepares procurement files by evaluating equipment, accessories, spare parts, and training needs together.</p>'), 'Technical compatibility focus in tactical communications, sensor, and optics requests.', 'Tactical Communications and Sensor Demand | Sultan Defense', 'Procurement notes on compatibility for tactical communications, sensors, optics, and simulation equipment.', 'tactical communications, sensor, optics, simulation'),
  ('nw020010-6010-4010-a010-nnnnnnnn0010', 'nw010005-5005-4005-9005-nnnnnnnn0005', 'en', 'NATO, AQAP, MIL-STD, NIJ, and NSN Standards', 'defense-standards-nato-aqap-mil-std-nij-nsn', JSON_OBJECT('html', '<p>Standards references make defense product quality and operational suitability easier to compare.</p><h2>Standard sets</h2><p>NATO, AQAP, MIL-STD, NIJ, ISO 9001, and NSN references mean different things by product family. The right standard must match the right use case.</p><h2>Document validation</h2><p>Sultan Defense checks certificates and technical documents inside the offer file to support buyer decisions.</p>'), 'A short guide to standards and certificate references in defense procurement.', 'Defense Standards | Sultan Defense', 'The role of NATO, AQAP, MIL-STD, NIJ, ISO 9001, and NSN standards in defense procurement.', 'NATO, AQAP, MIL-STD, NIJ, NSN')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `slug` = VALUES(`slug`),
  `content` = VALUES(`content`),
  `summary` = VALUES(`summary`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `tags` = VALUES(`tags`);

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
