-- Sultan Defense — Hakkımızda (about) içeriği (TR+EN). Kaynak: docs/content. 'A to Z' KULLANILMAZ.
SET NAMES utf8mb4;
UPDATE `custom_pages_i18n` SET
  `title`='Sultan Defense Hakkında — 1996''dan Beri Küresel Güvenlikte Güvenilir Ortağınız',
  `summary`='1996 yılında kurulan Sultan Defense Ltd., Co., savunma ve askeri sektörde önde gelen bir tedarikçi ve küresel tedarik ortağıdır.',
  `meta_title`='Hakkımızda | Sultan Defense',
  `meta_description`='1996''dan beri savunma sanayinde güvenilir tedarik ve ihracat ortağı. Orta Doğu, Türk Cumhuriyetleri ve Afrika için uçtan uca askeri tedarik çözümleri.',
  `content`='{"html": "<p>1996 yılında kurulan <strong>Sultan Defense Ltd., Co.</strong>, savunma ve askeri sektörde önde gelen bir tedarikçi ve küresel tedarik ortağıdır. Onlarca yıldır dünya genelinde silahlı kuvvetlere, kolluk kuvvetlerine ve güvenlik birimlerine üst düzey taktik, lojistik ve teknolojik çözümler sunmaya kendimizi adadık.</p><p>Stratejik olarak Türkiye merkezli yapımızla, Türk savunma sanayisinin hızla büyüyen yerli üretim kapasitesini, ileri Ar-Ge gücünü ve yenilikçi teknolojilerini gururla değerlendiriyoruz. Uzmanlaşmış bir savunma tedarikçisi olarak misyonumuz, ileri askeri mühendislik ile müşterilerimizin kritik ihtiyaçları arasında köprü kurmak ve her görevde operasyonel mükemmelliği sağlamaktır.</p><h2>Neden Sultan Defense?</h2><p>Savunma sektöründe güvenilirliğin bir ulusal güvenlik meselesi olduğunu biliyoruz. Öne çıkan avantajlarımız:</p><ul><li><strong>Eşsiz Fiyat-Performans Dengesi:</strong> Modern savunma bütçelerine göre optimize edilmiş üstün kaliteli ekipman.</li><li><strong>Yenilikçi ve Yerli Teknolojiler:</strong> Türk savunma yeniliklerinin ve güçlü üretim kabiliyetlerinin en önüne erişim.</li><li><strong>Hızlı Küresel Teslimat:</strong> Hedef neresi olursa olsun hızlı, güvenli ve zamanında tedarik sağlayan akıcı lojistik.</li><li><strong>Stratejik Bölgesel Odak:</strong> Orta Doğu, Türk Cumhuriyetleri ve Afrika''nın operasyonel ve çevresel gereksinimlerinde derin uzmanlık.</li></ul><p>Balistik korumadan deniz ve marine sistemlerine kadar Sultan Defense, görev-kritik çözümler için tek kaynaktan tedarik merkezinizdir. Yalnızca ekipman sağlamıyoruz; güven, dayanıklılık ve teknolojik üstünlük sunuyoruz.</p>"}', `updated_at`=NOW(3)
WHERE `page_id`='bc010001-5001-4001-9001-cccccccc0001' AND `locale`='tr';
UPDATE `custom_pages_i18n` SET
  `title`='About Sultan Defense — Your Trusted Partner in Global Security Since 1996',
  `summary`='Established in 1996, Sultan Defense Ltd., Co. is a premier supplier and global procurement partner in the defense and military sector.',
  `meta_title`='About Us | Sultan Defense',
  `meta_description`='A trusted defense procurement and export partner since 1996. End-to-end military procurement solutions for the Middle East, Turkic Republics and Africa.',
  `content`='{"html": "<p>Established in 1996, <strong>Sultan Defense Ltd., Co.</strong> is a premier supplier and global procurement partner in the defense and military sector. For decades, we have been dedicated to providing top-tier tactical, logistical, and technological solutions to armed forces, law enforcement, and security agencies across the globe.</p><p>Strategically headquartered in Turkey, we proudly leverage the Turkish defense industry''s rapidly expanding domestic production capacity, cutting-edge R&amp;D strength, and innovative technologies. As a specialized defense supplier, our mission is to bridge the gap between advanced military engineering and the critical needs of our clients, ensuring operational excellence in every mission.</p><h2>Why Choose Sultan Defense?</h2><p>We understand that in the defense sector, reliability is a matter of national security. Our distinct advantages include:</p><ul><li><strong>Unmatched Price-Performance Ratio:</strong> Delivering superior quality equipment optimized for modern defense budgets.</li><li><strong>Innovative &amp; Indigenous Technologies:</strong> Accessing the forefront of Turkish defense innovations and robust manufacturing capabilities.</li><li><strong>Rapid Global Delivery:</strong> Streamlined logistics ensuring fast, secure, and on-time procurement, regardless of the destination.</li><li><strong>Strategic Regional Focus:</strong> Deep expertise in the operational and environmental requirements of the Middle East, Turkic Republics, and Africa.</li></ul><p>From ballistic protection to naval and marine systems, Sultan Defense is your single-source procurement hub for mission-critical solutions. We do not just supply equipment; we deliver confidence, durability, and technological superiority.</p>"}', `updated_at`=NOW(3)
WHERE `page_id`='bc010001-5001-4001-9001-cccccccc0001' AND `locale`='en';
