-- =============================================================
-- FILE: 334_products_i18n_de_ar_ru.seed.sql
-- Sultan Defense product translations (de / ar / ru)
-- Adds German, Arabic, Russian rows to product_i18n
-- Composite PK (product_id, locale). slug + tags + specifications
-- copied verbatim from the EN rows (do NOT translate spec keys/tags).
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

START TRANSACTION;

INSERT INTO `product_i18n`
(`product_id`, `locale`, `title`, `slug`, `description`, `alt`, `tags`, `specifications`, `meta_title`, `meta_description`)
VALUES
  -- =========================================================
  -- SD-001 Ballistic Protection
  -- =========================================================
  ('sd000001-7001-4001-9001-dddddddd0001', 'de', 'Fortschrittlicher ballistischer Schutz und Körperpanzerung', 'ballistic-protection', '<p>Hochleistungsfähige ballistische Schutzausrüstung für maximale Überlebensfähigkeit gegen moderne Bedrohungen. Sultan Defense liefert taktische ballistische Westen, harte Schutzplatten, ballistische Helme und Fahrzeugpanzerungslösungen über lizenzierte türkische Verteidigungshersteller.</p>', 'Von Sultan Defense gelieferte ballistische Schutzausrüstung', JSON_ARRAY('ballistic protection','body armor','NIJ','helmets','armor plates'), JSON_OBJECT('solutions','Tactical vests, hard armor plates, helmets, vehicle armor','standards','NIJ, ISO 9001, MIL-STD where applicable','regions','Middle East, Africa, Turkic Republics'), 'Fortschrittlicher ballistischer Schutz und Körperpanzerung | Sultan Defense', 'Beschaffen Sie taktische Westen, harte Schutzplatten, Helme und Fahrzeugpanzerung über Sultan Defense.'),
  ('sd000001-7001-4001-9001-dddddddd0001', 'ar', 'حماية باليستية متقدمة ودروع واقية للجسم', 'ballistic-protection', '<p>معدات حماية باليستية عالية الأداء لتحقيق أقصى قدر من القابلية للنجاة في مواجهة التهديدات الحديثة. توفر Sultan Defense سترات باليستية تكتيكية وألواح دروع صلبة وخوذات باليستية وحلول تدريع المركبات عبر مصنّعين أتراك مرخّصين في قطاع الدفاع.</p>', 'معدات الحماية الباليستية الموردة من Sultan Defense', JSON_ARRAY('ballistic protection','body armor','NIJ','helmets','armor plates'), JSON_OBJECT('solutions','Tactical vests, hard armor plates, helmets, vehicle armor','standards','NIJ, ISO 9001, MIL-STD where applicable','regions','Middle East, Africa, Turkic Republics'), 'حماية باليستية متقدمة ودروع واقية للجسم | Sultan Defense', 'احصل على السترات التكتيكية وألواح الدروع الصلبة والخوذات وتدريع المركبات عبر Sultan Defense.'),
  ('sd000001-7001-4001-9001-dddddddd0001', 'ru', 'Современная баллистическая защита и бронежилеты', 'ballistic-protection', '<p>Высокоэффективное баллистическое защитное снаряжение для максимальной выживаемости против современных угроз. Sultan Defense поставляет тактические баллистические жилеты, жёсткие бронепластины, баллистические шлемы и решения для бронирования транспортных средств через лицензированных турецких производителей оборонной продукции.</p>', 'Баллистическое защитное снаряжение от Sultan Defense', JSON_ARRAY('ballistic protection','body armor','NIJ','helmets','armor plates'), JSON_OBJECT('solutions','Tactical vests, hard armor plates, helmets, vehicle armor','standards','NIJ, ISO 9001, MIL-STD where applicable','regions','Middle East, Africa, Turkic Republics'), 'Современная баллистическая защита и бронежилеты | Sultan Defense', 'Закупка тактических жилетов, бронепластин, шлемов и бронирования транспорта через Sultan Defense.'),

  -- =========================================================
  -- SD-002 Communication & Command Electronics
  -- =========================================================
  ('sd000002-7002-4002-9002-dddddddd0002', 'de', 'Sichere militärische Kommunikation und Führungselektronik', 'communication-command-electronics', '<p>Verschlüsselte taktische Funkgeräte, Elektronik für Kommandozentralen, sichere Gegensprechanlagen und Unterstützung der elektronischen Kampfführung für eine widerstandsfähige Gefechtsfeldkoordination in anspruchsvollen Einsatzumgebungen.</p>', 'Militärische Kommunikations- und Führungselektronik', JSON_ARRAY('tactical radios','command electronics','encrypted communication','EW'), JSON_OBJECT('solutions','Manpack, handheld and vehicular radios, command center suites, secure intercoms','standards','NATO interoperability where applicable','regions','Middle East and Africa focused logistics'), 'Sichere militärische Kommunikation und Führungselektronik | Sultan Defense', 'Beschaffung verschlüsselter Funkgeräte und Führungselektronik für moderne militärische Operationen.'),
  ('sd000002-7002-4002-9002-dddddddd0002', 'ar', 'اتصالات عسكرية آمنة وإلكترونيات القيادة', 'communication-command-electronics', '<p>أجهزة لاسلكي تكتيكية مشفّرة وإلكترونيات لمراكز القيادة وأنظمة اتصال داخلي آمنة ودعم للحرب الإلكترونية لتنسيق ميداني صامد في بيئات العمليات الصعبة.</p>', 'إلكترونيات الاتصالات والقيادة العسكرية', JSON_ARRAY('tactical radios','command electronics','encrypted communication','EW'), JSON_OBJECT('solutions','Manpack, handheld and vehicular radios, command center suites, secure intercoms','standards','NATO interoperability where applicable','regions','Middle East and Africa focused logistics'), 'اتصالات عسكرية آمنة وإلكترونيات القيادة | Sultan Defense', 'توريد أجهزة لاسلكي مشفّرة وإلكترونيات قيادة للعمليات العسكرية الحديثة.'),
  ('sd000002-7002-4002-9002-dddddddd0002', 'ru', 'Защищённая военная связь и электроника управления', 'communication-command-electronics', '<p>Шифрованные тактические радиостанции, электроника командных пунктов, защищённые системы внутренней связи и средства радиоэлектронной борьбы для устойчивой координации на поле боя в сложных оперативных условиях.</p>', 'Электроника военной связи и управления', JSON_ARRAY('tactical radios','command electronics','encrypted communication','EW'), JSON_OBJECT('solutions','Manpack, handheld and vehicular radios, command center suites, secure intercoms','standards','NATO interoperability where applicable','regions','Middle East and Africa focused logistics'), 'Защищённая военная связь и электроника управления | Sultan Defense', 'Закупка шифрованных радиостанций и электроники управления для современных военных операций.'),

  -- =========================================================
  -- SD-003 Containerized Field Kitchen
  -- =========================================================
  ('sd000003-7003-4003-9003-dddddddd0003', 'de', 'Containerisierte Feldküchen und mobile Versorgungseinheiten', 'containerized-field-kitchen', '<p>Schnell verlegbare mobile Küchen, containerisierte Bäckereien, Hygieneeinheiten und Kühllagermodule, konzipiert zur Versorgung von Truppen in abgelegenen oder feindlichen Umgebungen.</p>', 'Containerisierte Feldküche und Versorgungseinheiten', JSON_ARRAY('field kitchen','containerized units','mobile bakery','hygiene'), JSON_OBJECT('solutions','Mobile kitchens, bakeries, shower and hygiene units, cold storage','deployment','Rapid-deployment ISO container configurations','use_case','Forward operating bases and off-grid camps'), 'Containerisierte Feldküchen und mobile Versorgungseinheiten | Sultan Defense', 'Beschaffung mobiler Feldküchen und modularer Versorgungseinheiten für militärische Einsätze.'),
  ('sd000003-7003-4003-9003-dddddddd0003', 'ar', 'مطابخ ميدانية حاوية ووحدات دعم متنقلة', 'containerized-field-kitchen', '<p>مطابخ متنقلة سريعة الانتشار ومخابز حاوية ووحدات نظافة ووحدات تخزين مبرّد مصمّمة لإعالة القوات في البيئات النائية أو المعادية.</p>', 'مطبخ ميداني حاوي ووحدات دعم', JSON_ARRAY('field kitchen','containerized units','mobile bakery','hygiene'), JSON_OBJECT('solutions','Mobile kitchens, bakeries, shower and hygiene units, cold storage','deployment','Rapid-deployment ISO container configurations','use_case','Forward operating bases and off-grid camps'), 'مطابخ ميدانية حاوية ووحدات دعم متنقلة | Sultan Defense', 'توريد مطابخ ميدانية متنقلة ووحدات دعم نمطية لعمليات الانتشار العسكري.'),
  ('sd000003-7003-4003-9003-dddddddd0003', 'ru', 'Контейнерные полевые кухни и мобильные модули обеспечения', 'containerized-field-kitchen', '<p>Быстроразвёртываемые мобильные кухни, контейнерные пекарни, санитарно-гигиенические модули и холодильные блоки, спроектированные для жизнеобеспечения войск в удалённых или враждебных условиях.</p>', 'Контейнерная полевая кухня и модули обеспечения', JSON_ARRAY('field kitchen','containerized units','mobile bakery','hygiene'), JSON_OBJECT('solutions','Mobile kitchens, bakeries, shower and hygiene units, cold storage','deployment','Rapid-deployment ISO container configurations','use_case','Forward operating bases and off-grid camps'), 'Контейнерные полевые кухни и мобильные модули обеспечения | Sultan Defense', 'Закупка мобильных полевых кухонь и модульных блоков обеспечения для военных развёртываний.'),

  -- =========================================================
  -- SD-004 Field Support & Logistics
  -- =========================================================
  ('sd000004-7004-4004-9004-dddddddd0004', 'de', 'Taktische Feldunterstützung und militärische Logistik', 'field-support-logistics', '<p>Taktische Zelte, verlegbare Wartungswerkstätten, Kraftstoff- und Wasserverteilungssysteme sowie robuste Materialumschlaggeräte für unterbrechungsfreie Feldoperationen.</p>', 'Ausrüstung für taktische Feldunterstützung und Logistik', JSON_ARRAY('field logistics','military tents','maintenance workshop','fuel water systems'), JSON_OBJECT('solutions','Shelters, distribution systems, repair stations, material handling','delivery','Secure freight by air, land, or sea','role','Supply chain continuity for front-line operations'), 'Taktische Feldunterstützung und militärische Logistik | Sultan Defense', 'Beschaffen Sie taktische Unterkünfte, Wartungswerkstätten und Logistikausrüstung.'),
  ('sd000004-7004-4004-9004-dddddddd0004', 'ar', 'دعم ميداني تكتيكي ولوجستيات عسكرية', 'field-support-logistics', '<p>خيام تكتيكية وورش صيانة قابلة للنشر وأنظمة توزيع الوقود والمياه ومعدات مناولة مواد متينة لضمان استمرارية العمليات الميدانية دون انقطاع.</p>', 'معدات الدعم الميداني التكتيكي واللوجستيات', JSON_ARRAY('field logistics','military tents','maintenance workshop','fuel water systems'), JSON_OBJECT('solutions','Shelters, distribution systems, repair stations, material handling','delivery','Secure freight by air, land, or sea','role','Supply chain continuity for front-line operations'), 'دعم ميداني تكتيكي ولوجستيات عسكرية | Sultan Defense', 'توريد المآوي التكتيكية وورش الصيانة ومعدات اللوجستيات.'),
  ('sd000004-7004-4004-9004-dddddddd0004', 'ru', 'Тактическая полевая поддержка и военная логистика', 'field-support-logistics', '<p>Тактические палатки, развёртываемые ремонтные мастерские, системы распределения топлива и воды, а также прочное погрузочно-разгрузочное оборудование для непрерывных полевых операций.</p>', 'Оборудование тактической полевой поддержки и логистики', JSON_ARRAY('field logistics','military tents','maintenance workshop','fuel water systems'), JSON_OBJECT('solutions','Shelters, distribution systems, repair stations, material handling','delivery','Secure freight by air, land, or sea','role','Supply chain continuity for front-line operations'), 'Тактическая полевая поддержка и военная логистика | Sultan Defense', 'Закупка тактических укрытий, ремонтных мастерских и логистического оборудования.'),

  -- =========================================================
  -- SD-005 Naval & Marine Systems
  -- =========================================================
  ('sd000005-7005-4005-9005-dddddddd0005', 'de', 'Marineverteidigung und maritime Sicherheitssysteme', 'naval-marine-systems', '<p>Küstenüberwachungssysteme, marine Elektronik in Militärqualität, Taucherunterstützungsausrüstung, Unterwassersicherheit und Schiffsschutzlösungen für die maritime Lagebilderfassung.</p>', 'Marine- und maritime Sicherheitssysteme', JSON_ARRAY('naval systems','marine security','coastal surveillance','sonar'), JSON_OBJECT('solutions','Radar, EO suites, marine communications, sonar, vessel protection','users','Navies, coast guards, maritime security agencies','focus','Harbor, coastal and vessel security'), 'Marineverteidigung und maritime Sicherheitssysteme | Sultan Defense', 'Beschaffung von Marine- und maritimen Systemen für Seesicherheit und Küstenverteidigung.'),
  ('sd000005-7005-4005-9005-dddddddd0005', 'ar', 'أنظمة الدفاع البحري والأمن البحري', 'naval-marine-systems', '<p>أنظمة مراقبة ساحلية وإلكترونيات بحرية بمواصفات عسكرية ومعدات دعم الغوّاصين وأمن تحت الماء وحلول حماية السفن لتعزيز الوعي بالمجال البحري.</p>', 'أنظمة الأمن البحري والملاحي', JSON_ARRAY('naval systems','marine security','coastal surveillance','sonar'), JSON_OBJECT('solutions','Radar, EO suites, marine communications, sonar, vessel protection','users','Navies, coast guards, maritime security agencies','focus','Harbor, coastal and vessel security'), 'أنظمة الدفاع البحري والأمن البحري | Sultan Defense', 'توريد أنظمة بحرية للأمن البحري والدفاع الساحلي.'),
  ('sd000005-7005-4005-9005-dddddddd0005', 'ru', 'Военно-морская оборона и системы морской безопасности', 'naval-marine-systems', '<p>Системы береговой охраны, морская электроника военного класса, оборудование поддержки водолазов, подводная безопасность и решения для защиты судов для обеспечения осведомлённости о морской обстановке.</p>', 'Военно-морские и морские системы безопасности', JSON_ARRAY('naval systems','marine security','coastal surveillance','sonar'), JSON_OBJECT('solutions','Radar, EO suites, marine communications, sonar, vessel protection','users','Navies, coast guards, maritime security agencies','focus','Harbor, coastal and vessel security'), 'Военно-морская оборона и системы морской безопасности | Sultan Defense', 'Закупка военно-морских и морских систем для морской безопасности и береговой обороны.'),

  -- =========================================================
  -- SD-006 Power, Battery & Generator
  -- =========================================================
  ('sd000006-7006-4006-9006-dddddddd0006', 'de', 'Militärische Stromversorgung, Batterien und Generatoren', 'power-battery-generator', '<p>Robuste taktische Dieselgeneratoren, wiederaufladbare Batterien in Militärqualität, Solar- und Hybridstromeinheiten sowie intelligente Verteilerknoten für netzunabhängige Verteidigungsoperationen.</p>', 'Militärische Strom-, Batterie- und Generatorsysteme', JSON_ARRAY('generator','battery','military power','hybrid power'), JSON_OBJECT('solutions','Diesel generators, lithium-ion batteries, hybrid power units, power distribution','environment','Extreme heat and remote field conditions','mission','Continuous power for command and electronic systems'), 'Militärische Strom-, Batterie- und Generatorsysteme | Sultan Defense', 'Beschaffung von Militärgeneratoren, Batterien und taktischem Energiemanagement.'),
  ('sd000006-7006-4006-9006-dddddddd0006', 'ar', 'مصادر طاقة عسكرية وبطاريات ومولّدات', 'power-battery-generator', '<p>مولّدات ديزل تكتيكية معزّزة وبطاريات قابلة لإعادة الشحن بمواصفات عسكرية ووحدات طاقة شمسية وهجينة ومراكز توزيع ذكية للعمليات الدفاعية خارج الشبكة.</p>', 'أنظمة الطاقة والبطاريات والمولّدات العسكرية', JSON_ARRAY('generator','battery','military power','hybrid power'), JSON_OBJECT('solutions','Diesel generators, lithium-ion batteries, hybrid power units, power distribution','environment','Extreme heat and remote field conditions','mission','Continuous power for command and electronic systems'), 'مصادر طاقة عسكرية وبطاريات ومولّدات | Sultan Defense', 'توريد المولّدات العسكرية والبطاريات وإدارة الطاقة التكتيكية.'),
  ('sd000006-7006-4006-9006-dddddddd0006', 'ru', 'Военные источники питания, аккумуляторы и генераторы', 'power-battery-generator', '<p>Защищённые тактические дизельные генераторы, перезаряжаемые аккумуляторы военного класса, солнечные и гибридные энергоблоки, а также интеллектуальные узлы распределения для автономных оборонных операций.</p>', 'Военные системы питания, аккумуляторов и генераторов', JSON_ARRAY('generator','battery','military power','hybrid power'), JSON_OBJECT('solutions','Diesel generators, lithium-ion batteries, hybrid power units, power distribution','environment','Extreme heat and remote field conditions','mission','Continuous power for command and electronic systems'), 'Военные источники питания, аккумуляторы и генераторы | Sultan Defense', 'Закупка военных генераторов, аккумуляторов и тактического управления энергией.'),

  -- =========================================================
  -- SD-007 Shield & Riot Control
  -- =========================================================
  ('sd000007-7007-4007-9007-dddddddd0007', 'de', 'Ausrüstung zur Aufstandsbekämpfung und taktische Schilde', 'shield-riot-control', '<p>Ineinandergreifende Schutzschilde, Aufstandsbekämpfungsanzüge, Helme mit Visieren, Schlagstöcke und nicht-tödliches Zubehör zur Menschenmengenkontrolle für Strafverfolgungs- und innere Sicherheitseinheiten.</p>', 'Schutzschilde zur Aufstandsbekämpfung und taktische Ausrüstung', JSON_ARRAY('riot shield','anti-riot suit','law enforcement','crowd control'), JSON_OBJECT('solutions','Shields, suits, helmets, batons, accessories','materials','Polycarbonate and blunt-trauma protection systems','users','Police, gendarmerie, internal security forces'), 'Ausrüstung zur Aufstandsbekämpfung und taktische Schilde | Sultan Defense', 'Professionelle Beschaffung von Aufstandsbekämpfungs- und taktischer Schildausrüstung.'),
  ('sd000007-7007-4007-9007-dddddddd0007', 'ar', 'معدات مكافحة الشغب والدروع التكتيكية', 'shield-riot-control', '<p>دروع متشابكة لمكافحة الشغب وبدلات مضادة للشغب وخوذات مزوّدة بواقيات للوجه وهراوات وملحقات غير قاتلة لإدارة الحشود لوحدات إنفاذ القانون والأمن الداخلي.</p>', 'دروع مكافحة الشغب والمعدات التكتيكية', JSON_ARRAY('riot shield','anti-riot suit','law enforcement','crowd control'), JSON_OBJECT('solutions','Shields, suits, helmets, batons, accessories','materials','Polycarbonate and blunt-trauma protection systems','users','Police, gendarmerie, internal security forces'), 'معدات مكافحة الشغب والدروع التكتيكية | Sultan Defense', 'توريد احترافي لمعدات مكافحة الشغب والدروع التكتيكية.'),
  ('sd000007-7007-4007-9007-dddddddd0007', 'ru', 'Снаряжение для подавления беспорядков и тактические щиты', 'shield-riot-control', '<p>Сцепляемые противоударные щиты, защитные костюмы для разгона беспорядков, шлемы с забралами, дубинки и нелетальные средства управления толпой для правоохранительных органов и подразделений внутренней безопасности.</p>', 'Щиты для подавления беспорядков и тактическое снаряжение', JSON_ARRAY('riot shield','anti-riot suit','law enforcement','crowd control'), JSON_OBJECT('solutions','Shields, suits, helmets, batons, accessories','materials','Polycarbonate and blunt-trauma protection systems','users','Police, gendarmerie, internal security forces'), 'Снаряжение для подавления беспорядков и тактические щиты | Sultan Defense', 'Профессиональная закупка снаряжения для подавления беспорядков и тактических щитов.'),

  -- =========================================================
  -- SD-008 Surveillance, Sensors & Security
  -- =========================================================
  ('sd000008-7008-4008-9008-dddddddd0008', 'de', 'Militärische Überwachung und Sensoren zur Perimetersicherung', 'surveillance-sensors-security', '<p>Langstrecken-EO/IR-Kameras, Sensoren zur Erkennung von Perimetereindringlingen, taktische UAV und Bodenüberwachungsradare für ein Echtzeit-Lagebewusstsein und den Schutz kritischer Infrastruktur.</p>', 'Überwachungssensoren und Systeme zur Perimetersicherung', JSON_ARRAY('EO/IR','thermal camera','UAV','perimeter security','radar'), JSON_OBJECT('solutions','Thermal cameras, seismic/acoustic/fiber sensors, UAVs, radars','mission','Border, base and critical infrastructure security','response','Real-time detection and monitoring'), 'Militärische Überwachung und Sensoren zur Perimetersicherung | Sultan Defense', 'Beschaffung von EO/IR-Kameras, Sensoren, UAV und Radaren für Sicherheitsoperationen.'),
  ('sd000008-7008-4008-9008-dddddddd0008', 'ar', 'مراقبة عسكرية وأجهزة استشعار لأمن المحيط', 'surveillance-sensors-security', '<p>كاميرات EO/IR بعيدة المدى وأجهزة استشعار لكشف اختراق المحيط وطائرات UAV تكتيكية ورادارات مراقبة أرضية لتحقيق وعي ظرفي آني وحماية البنية التحتية الحيوية.</p>', 'أجهزة استشعار المراقبة وأنظمة أمن المحيط', JSON_ARRAY('EO/IR','thermal camera','UAV','perimeter security','radar'), JSON_OBJECT('solutions','Thermal cameras, seismic/acoustic/fiber sensors, UAVs, radars','mission','Border, base and critical infrastructure security','response','Real-time detection and monitoring'), 'مراقبة عسكرية وأجهزة استشعار لأمن المحيط | Sultan Defense', 'توريد كاميرات EO/IR وأجهزة استشعار وطائرات UAV ورادارات لعمليات الأمن.'),
  ('sd000008-7008-4008-9008-dddddddd0008', 'ru', 'Военное наблюдение и датчики охраны периметра', 'surveillance-sensors-security', '<p>Камеры EO/IR большой дальности, датчики обнаружения проникновения по периметру, тактические UAV и радары наземного наблюдения для ситуационной осведомлённости в реальном времени и защиты критической инфраструктуры.</p>', 'Датчики наблюдения и системы охраны периметра', JSON_ARRAY('EO/IR','thermal camera','UAV','perimeter security','radar'), JSON_OBJECT('solutions','Thermal cameras, seismic/acoustic/fiber sensors, UAVs, radars','mission','Border, base and critical infrastructure security','response','Real-time detection and monitoring'), 'Военное наблюдение и датчики охраны периметра | Sultan Defense', 'Закупка камер EO/IR, датчиков, UAV и радаров для операций безопасности.'),

  -- =========================================================
  -- SD-009 Tactical Gear & Textile
  -- =========================================================
  ('sd000009-7009-4009-9009-dddddddd0009', 'de', 'Militärbekleidung und taktische Ausrüstungstextilien', 'tactical-gear-textile', '<p>Kampfuniformen, MOLLE-Tragesysteme, taktische Gürtel, wasserdichtes militärisches Schuhwerk und Ausrüstung für extreme Witterungsbedingungen, bezogen über das großvolumige Textilfertigungsökosystem der Türkei.</p>', 'Militärbekleidung und taktische Textilausrüstung', JSON_ARRAY('combat uniform','MOLLE','tactical boots','military textile'), JSON_OBJECT('solutions','Uniforms, load-bearing gear, belts, boots, weather gear','capability','High-volume textile procurement','environment','Extreme heat, cold and rough terrain'), 'Militärbekleidung und taktische Ausrüstungstextilien | Sultan Defense', 'Beschaffung von Kampfuniformen, taktischer Ausrüstung und Militärtextilien.'),
  ('sd000009-7009-4009-9009-dddddddd0009', 'ar', 'ملابس عسكرية ومنسوجات المعدات التكتيكية', 'tactical-gear-textile', '<p>بدلات قتالية ومعدات حمل MOLLE وأحزمة تكتيكية وأحذية عسكرية مقاومة للماء ومعدات للأحوال الجوية القاسية، يتم توريدها عبر منظومة التصنيع النسيجي عالية الإنتاج في تركيا.</p>', 'الملابس العسكرية ومعدات المنسوجات التكتيكية', JSON_ARRAY('combat uniform','MOLLE','tactical boots','military textile'), JSON_OBJECT('solutions','Uniforms, load-bearing gear, belts, boots, weather gear','capability','High-volume textile procurement','environment','Extreme heat, cold and rough terrain'), 'ملابس عسكرية ومنسوجات المعدات التكتيكية | Sultan Defense', 'توريد البدلات القتالية والمعدات التكتيكية والمنسوجات العسكرية.'),
  ('sd000009-7009-4009-9009-dddddddd0009', 'ru', 'Военное обмундирование и тактические текстильные изделия', 'tactical-gear-textile', '<p>Боевая форма, разгрузочные системы MOLLE, тактические ремни, водонепроницаемая военная обувь и снаряжение для экстремальных погодных условий, поставляемые через крупнообъёмную текстильную производственную экосистему Турции.</p>', 'Военное обмундирование и тактическое текстильное снаряжение', JSON_ARRAY('combat uniform','MOLLE','tactical boots','military textile'), JSON_OBJECT('solutions','Uniforms, load-bearing gear, belts, boots, weather gear','capability','High-volume textile procurement','environment','Extreme heat, cold and rough terrain'), 'Военное обмундирование и тактические текстильные изделия | Sultan Defense', 'Закупка боевой формы, тактического снаряжения и военного текстиля.'),

  -- =========================================================
  -- SD-010 Training & Simulation Software
  -- =========================================================
  ('sd000010-7010-4010-9010-dddddddd0010', 'de', 'Gefechtstrainingssimulatoren und Software', 'training-simulation-software', '<p>Virtuelle Schießausbildungssysteme, taktische Konvoi- und Fahrzeugsimulatoren, Software für Führungs- und Planspielzwecke sowie Flug- und Marinesimulationsumgebungen für eine sichere Gefechtsbereitschaft.</p>', 'Software zur Gefechtstrainingssimulation', JSON_ARRAY('simulation','marksmanship','C2','training software','wargaming'), JSON_OBJECT('solutions','Marksmanship, convoy, C2, flight and naval simulators','benefit','Reduced training risk and live-fire cost','users','Defense academies and training centers'), 'Gefechtstrainingssimulatoren und Software | Sultan Defense', 'Beschaffung von Trainingssimulation und Verteidigungssoftware für die Gefechtsbereitschaft.'),
  ('sd000010-7010-4010-9010-dddddddd0010', 'ar', 'محاكيات تدريب قتالي وبرمجيات', 'training-simulation-software', '<p>أنظمة تدريب رماية افتراضية ومحاكيات قوافل ومركبات تكتيكية وبرمجيات ألعاب حرب للقيادة والسيطرة وبيئات محاكاة جوية وبحرية لجاهزية قتالية آمنة.</p>', 'برمجيات محاكاة التدريب القتالي', JSON_ARRAY('simulation','marksmanship','C2','training software','wargaming'), JSON_OBJECT('solutions','Marksmanship, convoy, C2, flight and naval simulators','benefit','Reduced training risk and live-fire cost','users','Defense academies and training centers'), 'محاكيات تدريب قتالي وبرمجيات | Sultan Defense', 'توريد محاكاة التدريب وبرمجيات الدفاع لتحقيق الجاهزية القتالية.'),
  ('sd000010-7010-4010-9010-dddddddd0010', 'ru', 'Симуляторы боевой подготовки и программное обеспечение', 'training-simulation-software', '<p>Виртуальные тренажёры стрелковой подготовки, тактические симуляторы колонн и транспортных средств, программное обеспечение для военных игр и управления, а также среды авиационной и военно-морской симуляции для безопасной боевой готовности.</p>', 'Программное обеспечение для симуляции боевой подготовки', JSON_ARRAY('simulation','marksmanship','C2','training software','wargaming'), JSON_OBJECT('solutions','Marksmanship, convoy, C2, flight and naval simulators','benefit','Reduced training risk and live-fire cost','users','Defense academies and training centers'), 'Симуляторы боевой подготовки и программное обеспечение | Sultan Defense', 'Закупка симуляции боевой подготовки и оборонного ПО для боевой готовности.')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `description` = VALUES(`description`),
  `alt` = VALUES(`alt`),
  `tags` = VALUES(`tags`),
  `specifications` = VALUES(`specifications`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`);

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
