-- =============================================================
-- FILE: 335_news_i18n_de_ar_ru.seed.sql
-- Sultan Defense — News (custom_pages_i18n) i18n (de, ar, ru)
-- Source: 310_sultandefense_news.seed.sql (translated from EN rows)
-- module_key = 'news'
-- Natural key: (page_id, locale). Slug = SAME as EN row for de/ar/ru.
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

START TRANSACTION;

INSERT INTO `custom_pages_i18n`
(`id`, `page_id`, `locale`, `title`, `slug`, `content`, `summary`, `meta_title`, `meta_description`, `tags`)
VALUES
  -- ============================================================
  -- POST 1 — Procurement Portfolio (slug: sultan-defense-procurement-portfolio)
  -- ============================================================
  (UUID(), 'nw010001-5001-4001-9001-nnnnnnnn0001', 'de', 'Sultan Defense veröffentlicht sein Beschaffungsportfolio für Verteidigung', 'sultan-defense-procurement-portfolio', JSON_OBJECT('html', '<p>Sultan Defense hat sein Beschaffungsportfolio veröffentlicht, das Landsysteme, ballistischen Schutz, taktische Textilien, Optik, Elektronik und logistische Unterstützung umfasst.</p><h2>B2B-Katalogfokus</h2><p>Der Katalog präsentiert Produktfamilien in einer klaren und vergleichbaren Struktur für öffentliche Einrichtungen, Sicherheitseinheiten und autorisierte gewerbliche Käufer.</p><h2>Beschaffungsablauf</h2><p>Anforderungsaufnahme, Herstellervalidierung, Exportkonformität, Qualitätsabnahme und Versandplanung werden als ein einziger Arbeitsablauf gesteuert.</p>'), 'Ankündigung des Beschaffungsportfolios und der B2B-Katalogstruktur von Sultan Defense.', 'Sultan Defense Beschaffungsportfolio | Nachrichten', 'Sultan Defense veröffentlicht sein Beschaffungsportfolio für Landsysteme, ballistischen Schutz, taktische Textilien, Optik und Elektronik.', 'Verteidigungsbeschaffung, B2B-Katalog, Sultan Defense'),
  (UUID(), 'nw010001-5001-4001-9001-nnnnnnnn0001', 'ar', 'سلطان ديفنس تنشر محفظة مشترياتها الدفاعية', 'sultan-defense-procurement-portfolio', JSON_OBJECT('html', '<p>أعلنت Sultan Defense عن نشر محفظة مشترياتها التي تشمل الأنظمة البرية والحماية الباليستية والمنسوجات التكتيكية والبصريات والإلكترونيات وعناصر الدعم اللوجستي.</p><h2>تركيز على كتالوج B2B</h2><p>يعرض الكتالوج عائلات المنتجات بهيكل واضح وقابل للمقارنة للمؤسسات الحكومية والوحدات الأمنية والمشترين التجاريين المعتمدين.</p><h2>سير عمل المشتريات</h2><p>تُدار مراحل استلام المتطلبات والتحقق من المُصنّع والامتثال للتصدير وقبول الجودة وتخطيط الشحن ضمن سير عمل واحد.</p>'), 'إعلان عن محفظة مشتريات Sultan Defense وهيكل كتالوج B2B.', 'محفظة مشتريات Sultan Defense | الأخبار', 'تنشر Sultan Defense محفظة مشترياتها للأنظمة البرية والحماية الباليستية والمنسوجات التكتيكية والبصريات والإلكترونيات.', 'مشتريات دفاعية, كتالوج B2B, Sultan Defense'),
  (UUID(), 'nw010001-5001-4001-9001-nnnnnnnn0001', 'ru', 'Sultan Defense публикует свой портфель оборонных закупок', 'sultan-defense-procurement-portfolio', JSON_OBJECT('html', '<p>Компания Sultan Defense опубликовала свой закупочный портфель, охватывающий наземные системы, баллистическую защиту, тактический текстиль, оптику, электронику и элементы логистической поддержки.</p><h2>Фокус на каталоге B2B</h2><p>Каталог представляет товарные группы в понятной и сопоставимой структуре для государственных учреждений, подразделений безопасности и авторизованных коммерческих покупателей.</p><h2>Процесс закупок</h2><p>Сбор требований, проверка производителя, экспортный комплаенс, приёмка по качеству и планирование отгрузки управляются как единый рабочий процесс.</p>'), 'Анонс закупочного портфеля и структуры B2B-каталога Sultan Defense.', 'Закупочный портфель Sultan Defense | Новости', 'Sultan Defense публикует закупочный портфель по наземным системам, баллистической защите, тактическому текстилю, оптике и электронике.', 'оборонные закупки, B2B-каталог, Sultan Defense'),

  -- ============================================================
  -- POST 2 — EUC / Export Permit Review Flow (slug: euc-export-permit-review-flow)
  -- ============================================================
  (UUID(), 'nw010002-5002-4002-9002-nnnnnnnn0002', 'de', 'Neuer Prüfablauf für EUC- und Exportgenehmigungsunterlagen', 'euc-export-permit-review-flow', JSON_OBJECT('html', '<p>Sultan Defense hat einen standardisierten Vorprüfungsablauf für Endverbleibserklärungen (EUC) und Exportgenehmigungsunterlagen während der Angebotsphase eingeführt.</p><h2>Vorprüfung</h2><p>Käuferidentität, Endverwendung, Bestimmungsland, technische Produktcodes und Dokumentenkonsistenz werden frühzeitig geprüft.</p><h2>Weniger Verzögerungen</h2><p>Um Verzögerungen durch fehlende Dokumente zu verringern, werden Hersteller, Käufer und Logistikpartner über denselben Dokumentensatz koordiniert.</p>'), 'Standardisierter Prüfablauf für EUC, Exportgenehmigungen und Dokumentenkonsistenz.', 'EUC- und Exportgenehmigungs-Prüfablauf | Sultan Defense', 'Sultan Defense wendet einen neuen Vorprüfungsablauf für Endverbleibserklärungen, Exportgenehmigungen und Dokumentenkonformität an.', 'EUC, Exportgenehmigung, export compliance'),
  (UUID(), 'nw010002-5002-4002-9002-nnnnnnnn0002', 'ar', 'سير عمل مراجعة جديد لشهادات المستخدم النهائي وملفات تصاريح التصدير', 'euc-export-permit-review-flow', JSON_OBJECT('html', '<p>أطلقت Sultan Defense سير عمل مراجعة مسبقة معياري لشهادات المستخدم النهائي (EUC) وملفات تصاريح التصدير خلال مرحلة عرض الأسعار.</p><h2>الفحص المسبق</h2><p>تُراجَع في مرحلة مبكرة هوية المشتري والاستخدام النهائي وبلد الوجهة والأكواد الفنية للمنتج واتساق المستندات.</p><h2>تقليل التأخير</h2><p>لتقليل التأخير الناجم عن المستندات الناقصة، يجري تنسيق المُصنّع والمشتري وأطراف اللوجستيات عبر مجموعة المستندات ذاتها.</p>'), 'سير عمل مراجعة معياري لشهادات المستخدم النهائي وتصاريح التصدير واتساق المستندات.', 'سير عمل مراجعة EUC وتصاريح التصدير | Sultan Defense', 'تطبّق Sultan Defense سير عمل مراجعة مسبقة جديداً لشهادات المستخدم النهائي وتصاريح التصدير والامتثال المستندي.', 'EUC, تصريح تصدير, export compliance'),
  (UUID(), 'nw010002-5002-4002-9002-nnnnnnnn0002', 'ru', 'Новый порядок проверки для EUC и файлов экспортных разрешений', 'euc-export-permit-review-flow', JSON_OBJECT('html', '<p>Компания Sultan Defense внедрила стандартный порядок предварительной проверки сертификатов конечного пользователя (EUC) и файлов экспортных разрешений на этапе подготовки предложения.</p><h2>Предварительная проверка</h2><p>На раннем этапе проверяются идентификация покупателя, конечное использование, страна назначения, технические коды продукции и согласованность документов.</p><h2>Меньше задержек</h2><p>Чтобы сократить задержки из-за недостающих документов, производитель, покупатель и логистические стороны координируются по единому комплекту документов.</p>'), 'Стандартный порядок проверки для EUC, экспортных разрешений и согласованности документов.', 'Порядок проверки EUC и экспортных разрешений | Sultan Defense', 'Sultan Defense применяет новый порядок предварительной проверки сертификатов конечного пользователя, экспортных разрешений и комплаенса документов.', 'EUC, экспортное разрешение, export compliance'),

  -- ============================================================
  -- POST 3 — Regional Logistics (slug: regional-defense-logistics-planning)
  -- ============================================================
  (UUID(), 'nw010003-5003-4003-9003-nnnnnnnn0003', 'de', 'Logistikplanung für den Nahen Osten, Afrika und die Turkrepubliken', 'regional-defense-logistics-planning', JSON_OBJECT('html', '<p>Die Versandplanung für Verteidigungsprodukte verbindet Routenwahl, Zolldokumente, Verpackung, Transportart und Lieferbedingungen.</p><h2>Regionenspezifischer Ansatz</h2><p>Für den Nahen Osten, Afrika und die Turkrepubliken werden operative Anforderungen, Transitrisiken und lokale Einfuhrvorschriften Land für Land bewertet.</p><h2>Nachverfolgbarkeit</h2><p>Sultan Defense steuert die Dokumentenverfolgung und die Koordination der Beteiligten während der Lieferung zentral.</p>'), 'Eine kurze Anmerkung zu Verteidigungslogistik und Versandplanung für Zielregionen.', 'Regionale Verteidigungslogistikplanung | Sultan Defense', 'Logistikplanung für Verteidigungsprodukte mit Fokus auf den Nahen Osten, Afrika und die Turkrepubliken.', 'Militärlogistik, Verteidigungsversand, Zoll'),
  (UUID(), 'nw010003-5003-4003-9003-nnnnnnnn0003', 'ar', 'تخطيط لوجستي للشرق الأوسط وأفريقيا والجمهوريات التركية', 'regional-defense-logistics-planning', JSON_OBJECT('html', '<p>يجمع تخطيط شحن المنتجات الدفاعية بين اختيار المسار والمستندات الجمركية والتغليف ووسيلة النقل وشروط التسليم.</p><h2>نهج خاص بكل منطقة</h2><p>بالنسبة للشرق الأوسط وأفريقيا والجمهوريات التركية، تُقيَّم المتطلبات التشغيلية ومخاطر العبور وقواعد الاستيراد المحلية بلداً بلداً.</p><h2>إمكانية التتبع</h2><p>تدير Sultan Defense تتبع المستندات وتنسيق الأطراف المعنية مركزياً أثناء عملية التسليم.</p>'), 'ملاحظة موجزة حول اللوجستيات الدفاعية وتخطيط الشحن للمناطق المستهدفة.', 'التخطيط اللوجستي الدفاعي الإقليمي | Sultan Defense', 'تخطيط لوجستي للمنتجات الدفاعية يركّز على الشرق الأوسط وأفريقيا والجمهوريات التركية.', 'لوجستيات عسكرية, شحن دفاعي, جمارك'),
  (UUID(), 'nw010003-5003-4003-9003-nnnnnnnn0003', 'ru', 'Логистическое планирование для Ближнего Востока, Африки и тюркских республик', 'regional-defense-logistics-planning', JSON_OBJECT('html', '<p>Планирование отгрузки оборонной продукции объединяет выбор маршрута, таможенные документы, упаковку, способ транспортировки и условия поставки.</p><h2>Подход с учётом региона</h2><p>Для Ближнего Востока, Африки и тюркских республик операционные требования, транзитные риски и местные правила импорта оцениваются по каждой стране отдельно.</p><h2>Прослеживаемость</h2><p>Sultan Defense централизованно управляет отслеживанием документов и координацией участников в ходе поставки.</p>'), 'Краткая заметка об оборонной логистике и планировании отгрузки для целевых регионов.', 'Региональное оборонное логистическое планирование | Sultan Defense', 'Логистическое планирование оборонной продукции с акцентом на Ближний Восток, Африку и тюркские республики.', 'военная логистика, оборонная отгрузка, таможня'),

  -- ============================================================
  -- POST 4 — Tactical Comms & Sensors (slug: tactical-communications-sensor-demand)
  -- ============================================================
  (UUID(), 'nw010004-5004-4004-9004-nnnnnnnn0004', 'de', 'Steigende Nachfrage nach taktischer Kommunikation und Sensoren', 'tactical-communications-sensor-demand', JSON_OBJECT('html', '<p>Die Nachfrage nach taktischer Kommunikation, Sensoren, Optik und Simulationsausrüstung für Feldeinheiten und den Schutz kritischer Anlagen steigt.</p><h2>Kompatibilität zuerst</h2><p>Integration in bestehende Systeme, Frequenz, Leistung, Klimabeständigkeit und Schulungsbedarf stehen im Mittelpunkt der technischen Prüfung.</p><h2>Paketansatz</h2><p>Sultan Defense erstellt Beschaffungsunterlagen, indem Ausrüstung, Zubehör, Ersatzteile und Schulungsbedarf gemeinsam bewertet werden.</p>'), 'Fokus auf technische Kompatibilität bei Anfragen zu taktischer Kommunikation, Sensoren und Optik.', 'Nachfrage nach taktischer Kommunikation und Sensoren | Sultan Defense', 'Beschaffungshinweise zur Kompatibilität von taktischer Kommunikation, Sensoren, Optik und Simulationsausrüstung.', 'taktische Kommunikation, Sensor, Optik, Simulation'),
  (UUID(), 'nw010004-5004-4004-9004-nnnnnnnn0004', 'ar', 'تزايد الطلب على الاتصالات التكتيكية وأجهزة الاستشعار', 'tactical-communications-sensor-demand', JSON_OBJECT('html', '<p>يتزايد الطلب على معدات الاتصالات التكتيكية وأجهزة الاستشعار والبصريات والمحاكاة للوحدات الميدانية وأمن المنشآت الحيوية.</p><h2>التوافق أولاً</h2><p>يقع التكامل مع الأنظمة القائمة والتردد والطاقة وتحمّل الظروف المناخية والحاجة إلى التدريب في صميم المراجعة الفنية.</p><h2>نهج الحلول المتكاملة</h2><p>تُعِدّ Sultan Defense ملفات المشتريات من خلال تقييم المعدات والملحقات وقطع الغيار واحتياجات التدريب معاً.</p>'), 'التركيز على التوافق الفني في طلبات الاتصالات التكتيكية وأجهزة الاستشعار والبصريات.', 'الطلب على الاتصالات التكتيكية وأجهزة الاستشعار | Sultan Defense', 'ملاحظات مشتريات حول توافق الاتصالات التكتيكية وأجهزة الاستشعار والبصريات ومعدات المحاكاة.', 'اتصالات تكتيكية, مستشعر, بصريات, محاكاة'),
  (UUID(), 'nw010004-5004-4004-9004-nnnnnnnn0004', 'ru', 'Растущий спрос на тактическую связь и датчики', 'tactical-communications-sensor-demand', JSON_OBJECT('html', '<p>Растёт спрос на тактическую связь, датчики, оптику и симуляционное оборудование для полевых подразделений и охраны критически важных объектов.</p><h2>Совместимость прежде всего</h2><p>Интеграция с существующими системами, частота, мощность, устойчивость к климатическим условиям и потребности в обучении находятся в центре технической оценки.</p><h2>Комплексный подход</h2><p>Sultan Defense готовит закупочные досье, оценивая оборудование, аксессуары, запасные части и потребности в обучении в совокупности.</p>'), 'Акцент на технической совместимости в запросах по тактической связи, датчикам и оптике.', 'Спрос на тактическую связь и датчики | Sultan Defense', 'Закупочные заметки о совместимости тактической связи, датчиков, оптики и симуляционного оборудования.', 'тактическая связь, датчик, оптика, симуляция'),

  -- ============================================================
  -- POST 5 — Defense Standards (slug: defense-standards-nato-aqap-mil-std-nij-nsn)
  -- ============================================================
  (UUID(), 'nw010005-5005-4005-9005-nnnnnnnn0005', 'de', 'NATO-, AQAP-, MIL-STD-, NIJ- und NSN-Standards', 'defense-standards-nato-aqap-mil-std-nij-nsn', JSON_OBJECT('html', '<p>Standardreferenzen machen die Qualität und die operative Eignung von Verteidigungsprodukten besser vergleichbar.</p><h2>Standardsätze</h2><p>NATO-, AQAP-, MIL-STD-, NIJ-, ISO 9001- und NSN-Referenzen bedeuten je nach Produktfamilie Unterschiedliches. Der richtige Standard muss zum richtigen Anwendungsfall passen.</p><h2>Dokumentenprüfung</h2><p>Sultan Defense prüft Zertifikate und technische Dokumente innerhalb der Angebotsunterlagen, um die Kaufentscheidung zu unterstützen.</p>'), 'Ein kurzer Leitfaden zu Standards und Zertifikatsreferenzen in der Verteidigungsbeschaffung.', 'Verteidigungsstandards | Sultan Defense', 'Die Rolle der Standards NATO, AQAP, MIL-STD, NIJ, ISO 9001 und NSN in der Verteidigungsbeschaffung.', 'NATO, AQAP, MIL-STD, NIJ, NSN'),
  (UUID(), 'nw010005-5005-4005-9005-nnnnnnnn0005', 'ar', 'معايير NATO وAQAP وMIL-STD وNIJ وNSN', 'defense-standards-nato-aqap-mil-std-nij-nsn', JSON_OBJECT('html', '<p>تجعل المراجع المعيارية جودة المنتجات الدفاعية وملاءمتها التشغيلية أكثر قابلية للمقارنة.</p><h2>مجموعات المعايير</h2><p>تحمل مراجع NATO وAQAP وMIL-STD وNIJ وISO 9001 وNSN دلالات مختلفة بحسب عائلة المنتج. ويجب أن يتطابق المعيار الصحيح مع سيناريو الاستخدام الصحيح.</p><h2>التحقق من المستندات</h2><p>تتحقق Sultan Defense من الشهادات والمستندات الفنية داخل ملف العرض لدعم قرار المشتري.</p>'), 'دليل مختصر للمعايير والمراجع التصديقية في المشتريات الدفاعية.', 'المعايير الدفاعية | Sultan Defense', 'دور معايير NATO وAQAP وMIL-STD وNIJ وISO 9001 وNSN في المشتريات الدفاعية.', 'NATO, AQAP, MIL-STD, NIJ, NSN'),
  (UUID(), 'nw010005-5005-4005-9005-nnnnnnnn0005', 'ru', 'Стандарты NATO, AQAP, MIL-STD, NIJ и NSN', 'defense-standards-nato-aqap-mil-std-nij-nsn', JSON_OBJECT('html', '<p>Ссылки на стандарты делают качество и эксплуатационную пригодность оборонной продукции более сопоставимыми.</p><h2>Наборы стандартов</h2><p>Ссылки на NATO, AQAP, MIL-STD, NIJ, ISO 9001 и NSN означают разное в зависимости от товарной группы. Правильный стандарт должен соответствовать правильному сценарию применения.</p><h2>Проверка документов</h2><p>Sultan Defense проверяет сертификаты и технические документы внутри файла предложения, чтобы поддержать решение покупателя.</p>'), 'Краткое руководство по стандартам и сертификационным ссылкам в оборонных закупках.', 'Оборонные стандарты | Sultan Defense', 'Роль стандартов NATO, AQAP, MIL-STD, NIJ, ISO 9001 и NSN в оборонных закупках.', 'NATO, AQAP, MIL-STD, NIJ, NSN')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `slug` = VALUES(`slug`),
  `content` = VALUES(`content`),
  `summary` = VALUES(`summary`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `tags` = VALUES(`tags`),
  `updated_at` = NOW(3);

COMMIT;
