-- =============================================================
-- FILE: 337_news_extra_i18n_de_ar_ru.seed.sql
-- Sultan Defense — Extra News (custom_pages_i18n) i18n (de, ar, ru)
-- Source: EN rows for nw010007 (Yildirimhan ICBM) and nw010008 (SAHA 2026)
-- module_key = 'news'
-- Natural key: (page_id, locale). Slug = SAME as EN row for de/ar/ru.
-- content stored as a single-quoted SQL string holding valid JSON {"html":...}
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

START TRANSACTION;

INSERT INTO `custom_pages_i18n`
(`id`, `page_id`, `locale`, `title`, `slug`, `content`, `summary`, `meta_title`, `meta_description`, `tags`)
VALUES
  -- ============================================================
  -- POST 7 — Yildirimhan ICBM (slug: yildirimhan-intercontinental-ballistic-missile)
  -- ============================================================
  (UUID(), 'nw010007-5007-4007-9007-nnnnnnnn0007', 'de', 'Türkeis erste interkontinentale ballistische Rakete „Yildirimhan“ vorgestellt', 'yildirimhan-intercontinental-ballistic-missile', '{"html": "<p>Türkeis erste interkontinentale ballistische Rakete (ICBM), die <strong>Yildirimhan</strong>, wurde am 5. Mai 2026 auf der SAHA 2026, der internationalen Messe für Verteidigung, Luft- und Raumfahrtindustrie in İstanbul, der Öffentlichkeit vorgestellt.</p><p>Die vom Forschungs- und Entwicklungszentrum des türkischen Ministeriums für Nationale Verteidigung entwickelte Rakete soll über eine <strong>Reichweite von mehr als 6.000 km</strong>, eine Nutzlastkapazität von etwa <strong>3.000 kg</strong> sowie einen Geschwindigkeitsbereich zwischen Mach 9 und Mach 25 verfügen und ist damit das System mit der größten Reichweite im Bestand des Landes.</p><p>Nach Systemen mit kurzer und mittlerer Reichweite wie J-600T Yildirim, Bora und Tayfun stellt die Yildirimhan ein neues Niveau dar, das die türkische Verteidigungsindustrie bei Abschreckung und Schlagkraft auf große Entfernung erreicht hat.</p>"}', 'Mit einer Reichweite von mehr als 6.000 km wurde Yildirimhan auf der SAHA 2026 als das System mit der größten Reichweite im Bestand der Türkei vorgestellt.', 'Türkeis erste interkontinentale ballistische Rakete „Yildirimhan“ vorgestellt', 'Mit einer Reichweite von mehr als 6.000 km wurde Yildirimhan auf der SAHA 2026 als das System mit der größten Reichweite im Bestand der Türkei vorgestellt.', ''),
  (UUID(), 'nw010007-5007-4007-9007-nnnnnnnn0007', 'ar', 'الكشف عن أول صاروخ باليستي عابر للقارات في تركيا «يلدريمهان»', 'yildirimhan-intercontinental-ballistic-missile', '{"html": "<p>تم الكشف للعموم عن أول صاروخ باليستي عابر للقارات (ICBM) في تركيا، وهو <strong>يلدريمهان</strong>، في الخامس من مايو 2026 خلال معرض SAHA 2026 الدولي لصناعة الدفاع والطيران والفضاء في إسطنبول.</p><p>وطُوِّر الصاروخ في مركز البحث والتطوير التابع لوزارة الدفاع الوطني التركية، ويُذكر أنه يتميز <strong>بمدى يتجاوز 6,000 km</strong>، وقدرة حمولة تبلغ نحو <strong>3,000 kg</strong>، وسرعة تتراوح بين ماخ 9 وماخ 25 — مما يجعله النظام الأطول مدى في ترسانة البلاد.</p><p>وبعد أنظمة قصيرة ومتوسطة المدى مثل J-600T يلدريم وبورا وطيفون، يمثّل يلدريمهان مستوى جديداً بلغته الصناعة الدفاعية التركية في الردع والضرب بعيد المدى.</p>"}', 'بمدى يتجاوز 6,000 km، كُشف عن يلدريمهان في معرض SAHA 2026 بوصفه النظام الأطول مدى في ترسانة تركيا.', 'الكشف عن أول صاروخ باليستي عابر للقارات في تركيا «يلدريمهان»', 'بمدى يتجاوز 6,000 km، كُشف عن يلدريمهان في معرض SAHA 2026 بوصفه النظام الأطول مدى في ترسانة تركيا.', ''),
  (UUID(), 'nw010007-5007-4007-9007-nnnnnnnn0007', 'ru', 'Представлена первая в Турции межконтинентальная баллистическая ракета «Йылдырымхан»', 'yildirimhan-intercontinental-ballistic-missile', '{"html": "<p>Первая в Турции межконтинентальная баллистическая ракета (ICBM) <strong>Йылдырымхан</strong> была представлена публике 5 мая 2026 года на международной выставке оборонной, авиационной и космической промышленности SAHA 2026 в Стамбуле.</p><p>Ракета, разработанная научно-исследовательским центром Министерства национальной обороны Турции, по сообщениям, обладает <strong>дальностью свыше 6 000 km</strong>, массой полезной нагрузки около <strong>3 000 kg</strong> и скоростью в диапазоне от Маха 9 до Маха 25, что делает её системой с наибольшей дальностью в арсенале страны.</p><p>После систем малой и средней дальности, таких как J-600T Йылдырым, Бора и Тайфун, Йылдырымхан представляет новый уровень, достигнутый оборонной промышленностью Турции в области сдерживания и нанесения ударов на большую дальность.</p>"}', 'С дальностью свыше 6 000 km Йылдырымхан был представлен на SAHA 2026 как система с наибольшей дальностью в арсенале Турции.', 'Представлена первая в Турции межконтинентальная баллистическая ракета «Йылдырымхан»', 'С дальностью свыше 6 000 km Йылдырымхан был представлен на SAHA 2026 как система с наибольшей дальностью в арсенале Турции.', ''),

  -- ============================================================
  -- POST 8 — SAHA 2026 (slug: saha-2026-defence-aerospace-exhibition)
  -- ============================================================
  (UUID(), 'nw010008-5008-4008-9008-nnnnnnnn0008', 'de', 'SAHA 2026 Internationale Messe für Verteidigung, Luft- und Raumfahrtindustrie in İstanbul eröffnet', 'saha-2026-defence-aerospace-exhibition', '{"html": "<p>Die <strong>SAHA 2026 Internationale Messe für Verteidigung, Luft- und Raumfahrtindustrie</strong> fand vom 5. bis 9. Mai 2026 im İstanbul Expo Center statt.</p><p>Mit <strong>mehr als 1.700 Ausstellern</strong> aus über 120 Ländern auf einer Ausstellungsfläche von mehr als 100.000 m² bot die Veranstaltung eine Plattform, auf der die neuesten Produkte in den Bereichen Land, See, Luft, Raumfahrt, unbemannte Systeme und disruptive Technologien präsentiert wurden.</p><p>Mit Zehntausenden von B2B-, G2B- und G2G-Treffen bleibt die Messe ein zentraler Treffpunkt für das globale Beschaffungsökosystem der Verteidigung. Bei Sultan Defense verfolgen wir internationale Veranstaltungen, die unser Beschaffungsnetzwerk stärken, sehr aufmerksam.</p>"}', 'Mehr als 1.700 Aussteller aus über 120 Ländern kamen vom 5. bis 9. Mai 2026 auf der SAHA 2026 in İstanbul zusammen.', 'SAHA 2026 Internationale Messe für Verteidigung, Luft- und Raumfahrtindustrie in İstanbul eröffnet', 'Mehr als 1.700 Aussteller aus über 120 Ländern kamen vom 5. bis 9. Mai 2026 auf der SAHA 2026 in İstanbul zusammen.', ''),
  (UUID(), 'nw010008-5008-4008-9008-nnnnnnnn0008', 'ar', 'افتتاح معرض SAHA 2026 الدولي لصناعة الدفاع والطيران والفضاء في إسطنبول', 'saha-2026-defence-aerospace-exhibition', '{"html": "<p>أُقيم <strong>معرض SAHA 2026 الدولي لصناعة الدفاع والطيران والفضاء</strong> في مركز إسطنبول للمعارض خلال الفترة من 5 إلى 9 مايو 2026.</p><p>وبجمعه <strong>أكثر من 1,700 عارض</strong> من أكثر من 120 دولة على مساحة عرض تتجاوز 100,000 متر مربع، شكّل الحدث منصة لعرض أحدث المنتجات في قطاعات البر والبحر والجو والفضاء والأنظمة غير المأهولة والتقنيات الثورية.</p><p>وباستضافته عشرات الآلاف من اجتماعات B2B وG2B وG2G، يظل المعرض نقطة لقاء رئيسية لمنظومة المشتريات الدفاعية العالمية. ونحن في Sultan Defense نتابع عن كثب الفعاليات الدولية التي تعزّز شبكة مشترياتنا.</p>"}', 'تجمّع أكثر من 1,700 عارض من أكثر من 120 دولة في معرض SAHA 2026 بإسطنبول خلال الفترة من 5 إلى 9 مايو 2026.', 'افتتاح معرض SAHA 2026 الدولي لصناعة الدفاع والطيران والفضاء في إسطنبول', 'تجمّع أكثر من 1,700 عارض من أكثر من 120 دولة في معرض SAHA 2026 بإسطنبول خلال الفترة من 5 إلى 9 مايو 2026.', ''),
  (UUID(), 'nw010008-5008-4008-9008-nnnnnnnn0008', 'ru', 'В Стамбуле открылась международная выставка оборонной, авиационной и космической промышленности SAHA 2026', 'saha-2026-defence-aerospace-exhibition', '{"html": "<p><strong>Международная выставка оборонной, авиационной и космической промышленности SAHA 2026</strong> прошла в выставочном центре İstanbul Expo Center с 5 по 9 мая 2026 года.</p><p>Объединив <strong>более 1 700 экспонентов</strong> из более чем 120 стран на выставочной площади свыше 100 000 кв. м, мероприятие стало платформой для демонстрации новейшей продукции в сегментах наземных, морских, воздушных и космических систем, беспилотных комплексов и прорывных технологий.</p><p>Принимая десятки тысяч встреч в форматах B2B, G2B и G2G, выставка остаётся ключевой точкой притяжения для глобальной экосистемы оборонных закупок. В Sultan Defense мы внимательно следим за международными мероприятиями, укрепляющими нашу закупочную сеть.</p>"}', 'Более 1 700 экспонентов из более чем 120 стран собрались на SAHA 2026 в Стамбуле с 5 по 9 мая 2026 года.', 'В Стамбуле открылась международная выставка оборонной, авиационной и космической промышленности SAHA 2026', 'Более 1 700 экспонентов из более чем 120 стран собрались на SAHA 2026 в Стамбуле с 5 по 9 мая 2026 года.', '')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `slug` = VALUES(`slug`),
  `content` = VALUES(`content`),
  `summary` = VALUES(`summary`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `tags` = VALUES(`tags`),
  `updated_at` = NOW(3);

COMMIT;
